# ===== Behavior =====
shell_integration disabled
enable_audio_bell no
allow_remote_control yes
listen_on unix:/tmp/kitty-{kitty_pid}

# ===== Appearance =====
font_family family="Comic Code Ligatures"
font_size 10.25
modify_font cell_height 1px

tab_bar_style powerline
tab_powerline_style round

hide_window_decorations yes
window_margin_width 8 8 2 8
window_padding_width 16 16 2 16

# ===== Layout & Shortcuts =====
enabled_layouts fat:bias=70;full_size=1;mirrored=false,stack
map kitty_mod+m toggle_layout stack
map kitty_mod+enter launch --cwd=current
map kitty_mod+a select_tab
map kitty_mod+d detach_tab

# ===== Themes =====
include ./themes/auto.conf
